name: Deploy Static HTML to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create deployment package
        run: |
          mkdir deploy
          cp -r web/ deploy/
          cp -r scripts/ deploy/
          cp .infra/appspec.yml deploy/
          cd deploy
          zip -r ../app.zip .
      
      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://${{ secrets.S3_BUCKET }}/${{ github.sha }}.zip

      - name: Deploy using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name devops-challenge-nginx-web-app \
            --deployment-group-name devops-challenge-nginx-web-dg \
            --s3-location bucket=${{ secrets.S3_BUCKET }},key=${{ github.sha }}.zip,bundleType=zip
